config/urls.py
from django.contrib import admin
from django.urls import include, path
import sys
sys.path.append(r'\개인연구\config')
urlpatterns = [
    path('home/', include('home.urls')),
    path('admin/', admin.site.urls),
]

home/urls.py
from django.urls import path
from django.contrib import admin
import sys
sys.path.append(r'\config\home')
from .views import index, detail
app_name='home'
urlpatterns = [
    # ex: /home/
    path('', index, name='index'),
    # ex: /home/5/
    path('<int:person_id>/', detail, name='detail'),
]

home/models.py
from django.db import models

class Person(models.Model):
    person_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.person_text

home/views.py
from django.http import Http404
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.template import loader

import sys
sys.path.append(r'\config\home')

p=0
from .models import Person
list1=[' ',' ',' ',' ']
list2=[' ',' ',' ',' ']
list3=[' ',' ',' ',' ']
list4=[' ',' ',' ',' ']
list5=[' ',' ',' ',' ']
list6=[' ',' ',' ',' ']
list7=[' ',' ',' ',' ']
list8=[' ',' ',' ',' ']
list9=[' ',' ',' ',' ']
list10=[' ',' ',' ',' ']
list11=[' ',' ',' ',' ']
list12=[' ',' ',' ',' ']
list13=[' ',' ',' ',' ']
list14=[' ',' ',' ',' ']
list15=[' ',' ',' ',' ']
list16=[' ',' ',' ',' ']
list17=[' ',' ',' ',' ']
list18=[' ',' ',' ',' ']
list19=[' ',' ',' ',' ']


# ...
def index(request):
    rtot = Person.objects.order_by('-pub_date')
    r201 =rtot[72:]
    r202 =rtot[68:72]
    r203 =rtot[64:68]
    r204 =rtot[60:64]
    r205 =rtot[56:60]
    r206 =rtot[52:56]
    r207 =rtot[48:52]
    r208 =rtot[44:48]
    r209 =rtot[40:44]
    r210 =rtot[36:40]
    r211 =rtot[32:36]
    r212 =rtot[28:32]
    r213 =rtot[24:28]
    r214 =rtot[20:24]
    r215 =rtot[16:20]
    r216 =rtot[12:16]
    r217 =rtot[8:12]
    r218 =rtot[4:8]
    r101 =rtot[0:4]
    a=request.GET.get('time')
    if a==None:
        t = ' '
    else:
        t = request.GET.get('time')

    p = request.GET.get('per')
    if p == None:
        p== None
    else:
        p=int(p)
    c=0

    for person in r201:
        if person.id == p:
            list1[c]=t
            c=c+1
        else:
            c=c+1
    c=0

    for person in r202:
        if person.id == p:
            list2[c]=t
            c=c+1
        else:
            c=c+1
    c=0

    for person in r203:
        if person.id == p:
            list3[c]=t
            c=c+1
        else:
            c=c+1
    c=0

    for person in r204:
        if person.id == p:
            list4[c]=t
            c=c+1
        else:
            c=c+1
    c=0

    for person in r205:
        if person.id == p:
            list5[c]=t
            c=c+1
        else:
            c=c+1
    c=0

    for person in r206:
        if person.id == p:
            list6[c]=t
            c=c+1
        else:
            c=c+1
    c=0

    for person in r207:
        if person.id == p:
            list7[c]=t
            c=c+1
        else:
            c=c+1
    c=0

    for person in r208:
        if person.id == p:
            list8[c]=t
            c=c+1
        else:
            c=c+1
    c=0

    for person in r209:
        if person.id == p:
            list9[c]=t
            c=c+1
        else:
            c=c+1
    c=0

    for person in r210:
        if person.id == p:
            list10[c]=t
            c=c+1
        else:
            c=c+1
    c=0

    for person in r211:
        if person.id == p:
            list11[c]=t
            c=c+1
        else:
            c=c+1
    c=0

    for person in r212:
        if person.id == p:
            list12[c]=t
            c=c+1
        else:
            c=c+1
    c=0

    for person in r213:
        if person.id == p:
            list13[c]=t
            c=c+1
        else:
            c=c+1
    c=0

    for person in r214:
        if person.id == p:
            list14[c]=t
            c=c+1
        else:
            c=c+1
    c=0

    for person in r215:
        if person.id == p:
            list15[c]=t
            c=c+1
        else:
            c=c+1
    c=0

    for person in r216:
        if person.id == p:
            list16[c]=t
            c=c+1
        else:
            c=c+1
    c=0

    for person in r217:
        if person.id == p:
            list17[c]=t
            c=c+1
        else:
            c=c+1
    c=0

    for person in r218:
        if person.id == p:
            list18[c]=t
            c=c+1
        else:
            c=c+1
    c=0

    for person in r101:
        if person.id == p:
            list19[c]=t
            c=c+1
        else:
            c=c+1
    c=0
    context = {'r201': r201,'r202' : r202,'r203' : r203,'r204' : r204,'r205' : r205,'r206' : r206,'r207' : r207,'r208' : r208,'r209' : r209,'r210' : r210,'r211' : r211,'r212' : r212,'r213' : r213,'r214' : r214,'r215' : r215,'r216' : r216,'r217' : r217,'r218' : r218,'r101' : r101,'c' : c, 'list1' : list1, 'list2' : list2, 'list3' : list3, 'list4' : list4, 'list5' : list5, 'list6' : list6, 'list7' : list7, 'list8' : list8, 'list9' : list9, 'list10' : list10, 'list11' : list11, 'list12' : list12, 'list13' : list13, 'list14' : list14, 'list15' : list15, 'list16' : list16, 'list17' : list17, 'list18' : list18, 'list19' : list19}
    template = loader.get_template('home/index.html')
    return HttpResponse(template.render(context, request))

def detail(request, person_id):
    try:
        person = Person.objects.get(pk=person_id)
    except Person.DoesNotExist:
        raise Http404("Person does not exist")
    return render(request, 'home/detail.html', {'person': person})

home/templates/home/detail.html
<h1>{{ person.person_text }}</h1>
<html lang="ko">
  <head>
  <meta charset="utf-8">
    <title>HTML</title>
    <style>
      * {
        font-size: 16px;
        font-family: Consolas, sans-serif;
      }
    </style>
  </head>
  <body>
    <form method="get" action="{% url 'home:index' %}">
    {% csrf_token %}
      <label>외출 시간 : <input type="text" name="time"></label>
      <input type="submit" value="수정">
      <button onclick="location.href='http://127.0.0.1:8000/home/'">홈</button >
      <a>_______________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________</a>
      <input type="'hidden" name="per" value="{{ person.id }}"></input>
    </form>
  </body>
</html>

home/templates/home/index.html

{% if r201 %}
    <li><a>201</a></li>
        <ul>
            <div style="float: left;">
        {% for person in r201 %}
            <li><a href="/home/{{ person.id }}/">{{ person.person_text }}</a>&nbsp;&nbsp;&nbsp;</li>
        {% endfor %}
                <br><br>
        </ul>
            {% for i in list1 %}
                <li><a>{{ i }}</a></li>
            {% endfor %}
        <br><br>


    <li><a>202</a></li>
        <ul>
            <div style="float: left;">
        {% for person in r202 %}
            <li><a href="/home/{{ person.id }}/">{{ person.person_text }}</a>&nbsp;&nbsp;&nbsp;</li>
        {% endfor %}
                <br><br>
        </ul>
            {% for i in list2 %}
                <li><a>{{ i }}</a></li>
            {% endfor %}
        <br><br>


     <li><a>203</a></li>
        <ul>
            <div style="float: left;">
        {% for person in r203 %}
            <li><a href="/home/{{ person.id }}/">{{ person.person_text }}</a>&nbsp;&nbsp;&nbsp;</li>
        {% endfor %}
                <br><br>
        </ul>
            {% for i in list3 %}
                <li><a>{{ i }}</a></li>
            {% endfor %}
        <br><br>


     <li><a>204</a></li>
        <ul>
            <div style="float: left;">
        {% for person in r204 %}
            <li><a href="/home/{{ person.id }}/">{{ person.person_text }}</a>&nbsp;&nbsp;&nbsp;</li>
        {% endfor %}
                <br><br>
        </ul>
            {% for i in list4 %}
                <li><a>{{ i }}</a></li>
            {% endfor %}
        <br><br>


     <li><a>205</a></li>
        <ul>
            <div style="float: left;">
        {% for person in r205 %}
            <li><a href="/home/{{ person.id }}/">{{ person.person_text }}</a>&nbsp;&nbsp;&nbsp;</li>
        {% endfor %}
                <br><br>
        </ul>
            {% for i in list5 %}
                <li><a>{{ i }}</a></li>
            {% endfor %}
        <br><br>


     <li><a>206</a></li>
        <ul>
            <div style="float: left;">
        {% for person in r206 %}
            <li><a href="/home/{{ person.id }}/">{{ person.person_text }}</a>&nbsp;&nbsp;&nbsp;</li>
        {% endfor %}
                <br><br>
        </ul>
            {% for i in list6 %}
                <li><a>{{ i }}</a></li>
            {% endfor %}
        <br><br>


     <li><a>207</a></li>
        <ul>
            <div style="float: left;">
        {% for person in r207 %}
            <li><a href="/home/{{ person.id }}/">{{ person.person_text }}</a>&nbsp;&nbsp;&nbsp;</li>
        {% endfor %}
                <br><br>
        </ul>
            {% for i in list7 %}
                <li><a>{{ i }}</a></li>
            {% endfor %}
        <br><br>


     <li><a>208</a></li>
        <ul>
            <div style="float: left;">
        {% for person in r208 %}
            <li><a href="/home/{{ person.id }}/">{{ person.person_text }}</a>&nbsp;&nbsp;&nbsp;</li>
        {% endfor %}
                <br><br>
        </ul>
            {% for i in list8 %}
                <li><a>{{ i }}</a></li>
            {% endfor %}
        <br><br>


     <li><a>209</a></li>
        <ul>
            <div style="float: left;">
        {% for person in r209 %}
            <li><a href="/home/{{ person.id }}/">{{ person.person_text }}</a>&nbsp;&nbsp;&nbsp;</li>
        {% endfor %}
                <br><br>
        </ul>
            {% for i in list9 %}
                <li><a>{{ i }}</a></li>
            {% endfor %}
        <br><br>


     <li><a>210</a></li>
        <ul>
            <div style="float: left;">
        {% for person in r210 %}
            <li><a href="/home/{{ person.id }}/">{{ person.person_text }}</a>&nbsp;&nbsp;&nbsp;</li>
        {% endfor %}
                <br><br>
        </ul>
            {% for i in list10 %}
                <li><a>{{ i }}</a></li>
            {% endfor %}
        <br><br>


     <li><a>211</a></li>
        <ul>
            <div style="float: left;">
        {% for person in r211 %}
            <li><a href="/home/{{ person.id }}/">{{ person.person_text }}</a>&nbsp;&nbsp;&nbsp;</li>
        {% endfor %}
                <br><br>
        </ul>
            {% for i in list11 %}
                <li><a>{{ i }}</a></li>
            {% endfor %}
        <br><br>


     <li><a>212</a></li>
        <ul>
            <div style="float: left;">
        {% for person in r212 %}
            <li><a href="/home/{{ person.id }}/">{{ person.person_text }}</a>&nbsp;&nbsp;&nbsp;</li>
        {% endfor %}
                <br><br>
        </ul>
            {% for i in list12 %}
                <li><a>{{ i }}</a></li>
            {% endfor %}
        <br><br>


     <li><a>213</a></li>
        <ul>
            <div style="float: left;">
        {% for person in r213 %}
            <li><a href="/home/{{ person.id }}/">{{ person.person_text }}</a>&nbsp;&nbsp;&nbsp;</li>
        {% endfor %}
                <br><br>
        </ul>
            {% for i in list13 %}
                <li><a>{{ i }}</a></li>
            {% endfor %}
        <br><br>


     <li><a>214</a></li>
        <ul>
            <div style="float: left;">
        {% for person in r214 %}
            <li><a href="/home/{{ person.id }}/">{{ person.person_text }}</a>&nbsp;&nbsp;&nbsp;</li>
        {% endfor %}
                <br><br>
        </ul>
            {% for i in list14 %}
                <li><a>{{ i }}</a></li>
            {% endfor %}
        <br><br>


     <li><a>215</a></li>
        <ul>
            <div style="float: left;">
        {% for person in r215 %}
            <li><a href="/home/{{ person.id }}/">{{ person.person_text }}</a>&nbsp;&nbsp;&nbsp;</li>
        {% endfor %}
                <br><br>
        </ul>
            {% for i in list15 %}
                <li><a>{{ i }}</a></li>
            {% endfor %}
        <br><br>


     <li><a>216</a></li>
        <ul>
            <div style="float: left;">
        {% for person in r216 %}
            <li><a href="/home/{{ person.id }}/">{{ person.person_text }}</a>&nbsp;&nbsp;&nbsp;</li>
        {% endfor %}
                <br><br>
        </ul>
            {% for i in list16 %}
                <li><a>{{ i }}</a></li>
            {% endfor %}
        <br><br>


     <li><a>217</a></li>
        <ul>
            <div style="float: left;">
        {% for person in r217 %}
            <li><a href="/home/{{ person.id }}/">{{ person.person_text }}</a>&nbsp;&nbsp;&nbsp;</li>
        {% endfor %}
                <br><br>
        </ul>
            {% for i in list17 %}
                <li><a>{{ i }}</a></li>
            {% endfor %}
        <br><br>


     <li><a>218</a></li>
        <ul>
            <div style="float: left;">
        {% for person in r218 %}
            <li><a href="/home/{{ person.id }}/">{{ person.person_text }}</a>&nbsp;&nbsp;&nbsp;</li>
        {% endfor %}
                <br><br>
        </ul>
            {% for i in list18 %}
                <li><a>{{ i }}</a></li>
            {% endfor %}
        <br><br>


     <li><a>101</a></li>
        <ul>
            <div style="float: left;">
        {% for person in r101 %}
            <li><a href="/home/{{ person.id }}/">{{ person.person_text }}</a>&nbsp;&nbsp;&nbsp;</li>
        {% endfor %}
                <br><br>
        </ul>
            {% for i in list19 %}
                <li><a>{{ i }}</a></li>
            {% endfor %}
        <br><br>


{% else %}
    <p>No person are available.</p>
{% endif %}
